events {}

http {
    upstream knowkey_server {
        server knowkey-server:8000;
    }

    upstream knowkey_mcp {
        server knowkey-mcp:8001;
    }

    server {
        listen 80;

        # ====================== MCP ENDPOINT ======================

        location ~ ^/mcp(?:/|$) {
            proxy_pass http://knowkey_mcp$request_uri;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect off;
        }

        # ====================== MAIN DJANGO APP ======================
        location / {
            proxy_pass http://knowkey_server/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
