# Generated by Django 6.0.5 on 2026-05-21 21:42

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', 'pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('author_type', models.CharField(choices=[('user', 'User'), ('chatbot', 'Chat Bot'), ('agent', 'Cli Agent'), ('service', 'External Service')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NodeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Node Type',
                'verbose_name_plural': 'Node Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Relationship Type',
                'verbose_name_plural': 'Relationship Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(default=dict)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='core.author')),
                ('version_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='core.node')),
                ('node_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='core.nodetype')),
                ('tags', models.ManyToManyField(blank=True, related_name='nodes', to='core.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NodeRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.author')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='core.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='core.node')),
                ('relationship_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationships', to='core.relationshiptype')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('source', 'target', 'relationship_type')},
            },
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['node_type'], name='core_node_node_ty_69da29_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['is_archived'], name='core_node_is_arch_d76d64_idx'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['version_of'], name='core_node_version_b0fc3e_idx'),
        ),
    ]
