# Generated by Django 6.0.5 on 2026-05-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_type',
            field=models.CharField(choices=[('user', 'User'), ('chatbot', 'Chat Bot'), ('agent', 'Cli Agent'), ('service', 'External Service')], max_length=20),
        ),
    ]
