"""
Django settings for knowkey project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-o*u3aye$d6mnwavba%$)rmkvc7al#ex7!w1v9pw-p-3citg=!6",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

ADMIN_ENABLED = os.getenv("DJANGO_ADMIN_ENABLED", "True").lower() == "true"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Sessions
# https://docs.djangoproject.com/en/5.2/ref/settings/#sessions


CSRF_TRUSTED_ORIGINS = [os.getenv("DJANGO_ALLOWED_DOMAIN", "localhost")]

SESSION_COOKIE_DOMAIN = os.getenv("DJANGO_ALLOWED_DOMAIN", "localhost")
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_DOMAIN = os.getenv("DJANGO_ALLOWED_DOMAIN", "localhost")
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "Lax"

CORS_ALLOWED_ORIGINS = os.getenv("DJANGO_ALLOWED_DOMAIN", "localhost")

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]

CORS_EXPOSE_HEADERS = [
    "etag",
]

SESSION_COOKIE_DOMAIN = os.getenv("DJANGO_ALLOWED_DOMAIN", "localhost")
CSRF_COOKIE_DOMAIN = os.getenv("DJANGO_ALLOWED_DOMAIN", "localhost")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_filters",
    "knowkey.core",
    "knowkey.worker",
    "knowkey.api",
    "knowkey.mcp",
    "knowkey.web",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "knowkey.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "knowkey.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "knowkey"),
        "USER": os.getenv("POSTGRES_USER", "knowkey"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "knowkey123"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


# Django Rest Framework

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}


# Redis

REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")

# Theme settings

AVAILABLE_THEMES = [
    "nord",
    "dim",
    "light",
    "dark",
    "cupcake",
    "bumblebee",
    "emerald",
    "corporate",
    "synthwave",
    "retro",
    "cyberpunk",
    "valentine",
    "halloween",
    "garden",
    "forest",
    "aqua",
    "lofi",
    "pastel",
    "fantasy",
    "wireframe",
    "black",
    "luxury",
    "dracula",
    "cmyk",
    "autumn",
    "business",
    "acid",
    "lemonade",
    "night",
    "coffee",
    "winter",
    "sunset",
    "caramellatte",
    "abyss",
    "silk",
]
THEME_COOKIE_NAME = "theme"  # Name of the cookie
THEME_COOKIE_AGE = 365 * 24 * 60 * 60  # Cookie duration (1 year)
THEME_COOKIE_PATH = "/"  # Cookie path
THEME_COOKIE_DOMAIN = None  # Set to your domain if needed
THEME_COOKIE_SECURE = False  # True for HTTPS-only
THEME_COOKIE_HTTPONLY = False  # True to restrict JS access
THEME_COOKIE_SAMESITE = "Lax"  # Cookie SameSite policy
